name: 'Create Jira Tickets for Dependabot Vulnerabilities'
author: DevOps/BMiller
description: Create Jira Tickets for Dependabot Vulnerabilities

inputs:
  branch_action:
    description: 'Create, Recreate or Delete a branch database. Default is Create.'
    required: false
    default: 'Create'

runs:
  using: 'composite'  
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # - name: Run linting rules and tests
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
      
      # - name: Get Dependabot Alerts
      #   uses: actions/github-script@v7
      #   with: 
      #     script: |
      #       const fs = require('fs');
      #       let page = 1;
      #       let allAlerts = [];

      #       while (true) {
      #           const { data: alerts } = await github.rest.dependabot.listAlertsForRepo({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           per_page: 100,
      #           page,
      #           state: "open"
      #           });
                
      #           if (alerts.length === 0) break;
                
      #           allAlerts = allAlerts.concat(alerts);
      #           page++;
      #       }

      #       console.log(`Fetched ${allAlerts.length} total alerts for ${{ github.repository}}.`);

      #       fs.writeFileSync('alerts.json', JSON.stringify(allAlerts, null, 2));

    - name: Create Tickets
      shell: bash
      run: ./create-jira-tickets.sh

      # - shell: bash
      #   env:
      #     DATABASE: ${{ inputs.database_name }}
      #     USERNAME: ${{ inputs.github_actor }}
      #     SOURCE_DB: ${{ inputs.source_database_name }}
      #     ACTION: ${{ inputs.branch_action }}
      #     DB_CLUSTER: ${{ inputs.database_cluster }}
      #   run: bash ${{ github.action_path }}/script.sh